name: testing github actions

on:
  push:
    branches: [ main ]
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World from our first action!"
            